// Code generated by "stringer -type=FileType"; DO NOT EDIT

package archive

import "fmt"

const _FileType_name = "TypeDirTypeFifoTypeCharTypeBlockTypeRegularTypeSymlinkTypeSocket"

var _FileType_index = [...]uint8{0, 7, 15, 23, 32, 43, 54, 64}

func (i FileType) String() string {
	if i >= FileType(len(_FileType_index)-1) {
		return fmt.Sprintf("FileType(%d)", i)
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
