package elf

var mpdfiles = map[string]ef{
	"/usr/bin/mpd": {[]string{
		"libexpat.so.1",
		"libupnp.so.6",
		"libixml.so.2",
		"libmpdclient.so.2",
		"libcurl.so.4",
		"libnfs.so.11",
		"libsmbclient.so.0",
		"libFLAC.so.8",
		"libyajl.so.2",
		"libavahi-common.so.3",
		"libavahi-client.so.3",
		"libdbus-1.so.3",
		"libsqlite3.so.0",
		"libogg.so.0",
		"libvorbis.so.0",
		"libsndfile.so.1",
		"libaudiofile.so.1",
		"libgme.so.0",
		"libwavpack.so.1",
		"libmad.so.0",
		"libopus.so.0",
		"libavformat.so.57",
		"libavcodec.so.57",
		"libavutil.so.55",
		"libfaad.so.2",
		"libmodplug.so.1",
		"libcdio_paranoia.so.2",
		"libcdio_cdda.so.2",
		"libcdio.so.16",
		"libmms.so.0",
		"libm.so.6",
		"libasound.so.2",
		"libbz2.so.1.0",
		"libiso9660.so.10",
		"libzzip-0.so.13",
		"libao.so.4",
		"libjack.so.0",
		"libpthread.so.0",
		"libshout.so.3",
		"libpulse.so.0",
		"libid3tag.so.0",
		"libsoxr.so.0",
		"libsamplerate.so.0",
		"libmp3lame.so.0",
		"libvorbisenc.so.2",
		"libz.so.1",
		"libicui18n.so.59",
		"libicuuc.so.59",
		"libsystemd.so.0",
		"libstdc++.so.6",
		"libgcc_s.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libexpat.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libc.so.6": {[]string{
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/ld-linux-x86-64.so.2": {[]string(nil),
		[]string(nil),
		[]string(nil)},
	"/lib64/libupnp.so.6": {[]string{
		"libthreadutil.so.6",
		"libixml.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libthreadutil.so.6": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libpthread.so.0": {[]string{
		"libc.so.6",
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libixml.so.2": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libmpdclient.so.2": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libcurl.so.4": {[]string{
		"libnghttp2.so.14",
		"libssh2.so.1",
		"libpsl.so.5",
		"libssl.so.1.1",
		"libcrypto.so.1.1",
		"libgssapi_krb5.so.2",
		"libkrb5.so.3",
		"libk5crypto.so.3",
		"libcom_err.so.2",
		"libz.so.1",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libnghttp2.so.14": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libssh2.so.1": {[]string{
		"libssl.so.1.1",
		"libcrypto.so.1.1",
		"libz.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libssl.so.1.1": {[]string{
		"libcrypto.so.1.1",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libcrypto.so.1.1": {[]string{
		"libdl.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libdl.so.2": {[]string{
		"libc.so.6",
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libz.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libpsl.so.5": {[]string{
		"libicuuc.so.59",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libicuuc.so.59": {[]string{
		"libicudata.so.59",
		"libpthread.so.0",
		"libdl.so.2",
		"libstdc++.so.6",
		"libm.so.6",
		"libgcc_s.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libicudata.so.59": {[]string(nil),
		[]string(nil),
		[]string(nil)},
	"/lib64/libstdc++.so.6": {[]string{
		"libm.so.6",
		"libc.so.6",
		"ld-linux-x86-64.so.2",
		"libgcc_s.so.1"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libm.so.6": {[]string{
		"libc.so.6",
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgcc_s.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgssapi_krb5.so.2": {[]string{
		"libkrb5.so.3",
		"libk5crypto.so.3",
		"libcom_err.so.2",
		"libkrb5support.so.0",
		"libdl.so.2",
		"libkeyutils.so.1",
		"libresolv.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libkrb5.so.3": {[]string{
		"libk5crypto.so.3",
		"libcom_err.so.2",
		"libkrb5support.so.0",
		"libkeyutils.so.1",
		"libresolv.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libk5crypto.so.3": {[]string{
		"libkrb5support.so.0",
		"libkeyutils.so.1",
		"libresolv.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libkrb5support.so.0": {[]string{
		"libkeyutils.so.1",
		"libresolv.so.2",
		"libdl.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libkeyutils.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libresolv.so.2": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libcom_err.so.2": {[]string{
		"libpthread.so.0",
		"libc.so.6",
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libnfs.so.11": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsmbclient.so.0": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libmsrpc3-samba4.so",
		"liblibcli-lsa3-samba4.so",
		"liblibsmb-samba4.so",
		"libsamba-security-samba4.so",
		"libsmbconf.so.0",
		"libndr.so.0",
		"libsamba-debug-samba4.so",
		"libsamba-errors.so.1",
		"libtevent-util.so.0",
		"libgse-samba4.so",
		"libndr-standard.so.0",
		"libdcerpc-samba-samba4.so",
		"libcli-smb-common-samba4.so",
		"libutil-cmdline-samba4.so",
		"libsamba3-util-samba4.so",
		"libsecrets3-samba4.so",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libsamba-util.so.0": {[]string{
		"libpthread.so.0",
		"libtime-basic-samba4.so",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libreplace-samba4.so",
		"libsocket-blocking-samba4.so",
		"librt.so.1",
		"libsystemd.so.0",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libtime-basic-samba4.so": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libsamba-debug-samba4.so": {[]string{
		"libpthread.so.0",
		"libtime-basic-samba4.so",
		"libsocket-blocking-samba4.so",
		"libsystemd.so.0",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libsocket-blocking-samba4.so": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsystemd.so.0": {[]string{
		"libpthread.so.0",
		"libc.so.6",
		"libgcrypt.so.20",
		"librt.so.1",
		"liblzma.so.5",
		"liblz4.so.1",
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgcrypt.so.20": {[]string{
		"libgpg-error.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgpg-error.so.0": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/librt.so.1": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/liblzma.so.5": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/liblz4.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libtalloc.so.2": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libbsd.so.0": {[]string{
		"librt.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/samba/libgenrand-samba4.so": {[]string{
		"libpthread.so.0",
		"libsys-rw-samba4.so",
		"libsocket-blocking-samba4.so",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libsys-rw-samba4.so": {[]string{
		"libpthread.so.0",
		"libiov-buf-samba4.so",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libiov-buf-samba4.so": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/samba/libreplace-samba4.so": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libtevent.so.0": {[]string{
		"libtalloc.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/samba/libmsrpc3-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libtevent-util.so.0",
		"liblibsmb-samba4.so",
		"libsamba-credentials.so.0",
		"libndr-samba-samba4.so",
		"libsamba-hostconfig.so.0",
		"libdbwrap-samba4.so",
		"libcliauth-samba4.so",
		"libdcerpc-binding.so.0",
		"libutil-tdb-samba4.so",
		"libgse-samba4.so",
		"libndr-standard.so.0",
		"libdcerpc-samba-samba4.so",
		"libsamba-sockets-samba4.so",
		"libndr.so.0",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libsocket-blocking-samba4.so",
		"libsamba-errors.so.1",
		"libcli-smb-common-samba4.so",
		"libgensec-samba4.so",
		"libsmbconf.so.0",
		"libsamba3-util-samba4.so",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libtevent-util.so.0": {[]string{
		"libpthread.so.0",
		"libsamba-errors.so.1",
		"libtalloc.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libsamba-errors.so.1": {[]string{
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/liblibsmb-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libasn1util-samba4.so",
		"libcli-cldap-samba4.so",
		"libcliauth-samba4.so",
		"libCHARSET3-samba4.so",
		"libndr.so.0",
		"libcli-smb-common-samba4.so",
		"libgse-samba4.so",
		"libsamba-security-samba4.so",
		"libutil-cmdline-samba4.so",
		"libgensec-samba4.so",
		"libcom_err-samba4.so.0",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libsamba-errors.so.1",
		"libtevent-util.so.0",
		"libndr-nbt.so.0",
		"libsamba-hostconfig.so.0",
		"libsamba3-util-samba4.so",
		"libsmb-transport-samba4.so",
		"libsmbconf.so.0",
		"libsamba-credentials.so.0",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libasn1util-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libcli-cldap-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libtevent-util.so.0",
		"libsamba-sockets-samba4.so",
		"libndr-nbt.so.0",
		"libsamba-debug-samba4.so",
		"libsamba-errors.so.1",
		"libcli-ldap-common-samba4.so",
		"libsamba-security-samba4.so",
		"libndr.so.0",
		"libasn1util-samba4.so",
		"libldb.so.1",
		"libtalloc.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libsamba-sockets-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libiov-buf-samba4.so",
		"libsocket-blocking-samba4.so",
		"libinterfaces-samba4.so",
		"libsamba-errors.so.1",
		"libndr-nbt.so.0",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libinterfaces-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-debug-samba4.so",
		"libbsd.so.0",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64"}},
	"/lib64/libndr-nbt.so.0": {[]string{
		"libndr.so.0",
		"libsamba-security-samba4.so",
		"libsamba-util.so.0",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libndr.so.0": {[]string{
		"libsamba-util.so.0",
		"libsamba-errors.so.1",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libsamba-security-samba4.so": {[]string{
		"libndr.so.0",
		"libsamba-util.so.0",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libcli-ldap-common-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libsamba-errors.so.1",
		"libasn1util-samba4.so",
		"libndr.so.0",
		"libsamba-security-samba4.so",
		"libsamba-debug-samba4.so",
		"libldb.so.1",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libldb.so.1": {[]string{
		"libpthread.so.0",
		"libdl.so.2",
		"libtevent.so.0",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64"}},
	"/lib64/samba/libcliauth-samba4.so": {[]string{
		"libpthread.so.0",
		"libutil-tdb-samba4.so",
		"libasn1util-samba4.so",
		"libndr-samba-samba4.so",
		"libsamba-errors.so.1",
		"libsamba-hostconfig.so.0",
		"libndr.so.0",
		"libdbwrap-samba4.so",
		"libsamba-security-samba4.so",
		"libsamba-util.so.0",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libtalloc.so.2",
		"libtdb.so.1",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libutil-tdb-samba4.so": {[]string{
		"libtdb.so.1",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libtdb.so.1": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/samba/libndr-samba-samba4.so": {[]string{
		"libndr-standard.so.0",
		"libasn1util-samba4.so",
		"libndr-nbt.so.0",
		"libndr.so.0",
		"libsamba-security-samba4.so",
		"libsamba-debug-samba4.so",
		"libsamba-util.so.0",
		"libtalloc.so.2",
		"libz.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libndr-standard.so.0": {[]string{
		"libsamba-security-samba4.so",
		"libndr.so.0",
		"libsamba-util.so.0",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libsamba-hostconfig.so.0": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libserver-role-samba4.so",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libserver-role-samba4.so": {[]string{
		"libsamba-debug-samba4.so",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64"}},
	"/lib64/samba/libdbwrap-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libtdb-wrap-samba4.so",
		"libutil-tdb-samba4.so",
		"libsamba-errors.so.1",
		"libsamba-hostconfig.so.0",
		"libsamba-debug-samba4.so",
		"libtdb.so.1",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libtdb-wrap-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-debug-samba4.so",
		"libtdb.so.1",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libCHARSET3-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libsamba3-util-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libsamba3-util-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libreplace-samba4.so",
		"libutil-setid-samba4.so",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libutil-setid-samba4.so": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/samba/libcli-smb-common-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libiov-buf-samba4.so",
		"libsamba-errors.so.1",
		"libsmb-transport-samba4.so",
		"libndr.so.0",
		"libgensec-samba4.so",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libtevent-util.so.0",
		"libsamba-sockets-samba4.so",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libsmb-transport-samba4.so": {[]string{
		"libpthread.so.0",
		"libiov-buf-samba4.so",
		"libtevent-util.so.0",
		"libsocket-blocking-samba4.so",
		"libtalloc.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libgensec-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libwbclient.so.0",
		"libcom_err-samba4.so.0",
		"libsamba-modules-samba4.so",
		"libgssapi-samba4.so.2",
		"libtevent-util.so.0",
		"libauthkrb5-samba4.so",
		"libndr-samba-samba4.so",
		"libsamba-errors.so.1",
		"libasn1util-samba4.so",
		"libsamba-security-samba4.so",
		"libsamdb.so.0",
		"libsamba-debug-samba4.so",
		"libsamba-credentials.so.0",
		"libsamba-sockets-samba4.so",
		"libcliauth-samba4.so",
		"libtime-basic-samba4.so",
		"libgenrand-samba4.so",
		"libndr.so.0",
		"libkrb5samba-samba4.so",
		"libsamba-hostconfig.so.0",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libwbclient.so.0": {[]string{
		"libwinbind-client-samba4.so",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libwinbind-client-samba4.so": {[]string{
		"libpthread.so.0",
		"libreplace-samba4.so",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libcom_err-samba4.so.0": {[]string{
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libsamba-modules-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libsamba-errors.so.1",
		"libsamba-debug-samba4.so",
		"libdl.so.2",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64"}},
	"/lib64/samba/libgssapi-samba4.so.2": {[]string{
		"libpthread.so.0",
		"libkrb5-samba4.so.26",
		"libroken-samba4.so.19",
		"libasn1-samba4.so.8",
		"libhcrypto-samba4.so.5",
		"libheimbase-samba4.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libkrb5-samba4.so.26": {[]string{
		"libpthread.so.0",
		"libheimbase-samba4.so.1",
		"libcom_err-samba4.so.0",
		"libasn1-samba4.so.8",
		"libhx509-samba4.so.5",
		"libhcrypto-samba4.so.5",
		"libroken-samba4.so.19",
		"libwind-samba4.so.0",
		"libbsd.so.0",
		"libdl.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libheimbase-samba4.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libasn1-samba4.so.8": {[]string{
		"libroken-samba4.so.19",
		"libcom_err-samba4.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libroken-samba4.so.19": {[]string{
		"libpthread.so.0",
		"libresolv.so.2",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libhx509-samba4.so.5": {[]string{
		"libpthread.so.0",
		"libroken-samba4.so.19",
		"libasn1-samba4.so.8",
		"libhcrypto-samba4.so.5",
		"libcom_err-samba4.so.0",
		"libwind-samba4.so.0",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libhcrypto-samba4.so.5": {[]string{
		"libpthread.so.0",
		"libroken-samba4.so.19",
		"libasn1-samba4.so.8",
		"libdl.so.2",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libwind-samba4.so.0": {[]string{
		"libcom_err-samba4.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libauthkrb5-samba4.so": {[]string{
		"libpthread.so.0",
		"libndr.so.0",
		"libgssapi-samba4.so.2",
		"libauth-sam-reply-samba4.so",
		"libtevent-util.so.0",
		"libkrb5samba-samba4.so",
		"libndr-krb5pac.so.0",
		"libsamba-errors.so.1",
		"libsamba-hostconfig.so.0",
		"libsamba-sockets-samba4.so",
		"libsamba-util.so.0",
		"libkrb5-samba4.so.26",
		"libcom_err-samba4.so.0",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libgnutls.so.30",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libauth-sam-reply-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libsamba-security-samba4.so",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libkrb5samba-samba4.so": {[]string{
		"libpthread.so.0",
		"libkrb5-samba4.so.26",
		"libsamba-util.so.0",
		"libcom_err-samba4.so.0",
		"libgssapi-samba4.so.2",
		"libasn1-samba4.so.8",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libndr-krb5pac.so.0": {[]string{
		"libndr.so.0",
		"libndr-standard.so.0",
		"libsamba-security-samba4.so",
		"libsamba-util.so.0",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libgnutls.so.30": {[]string{
		"libz.so.1",
		"libp11-kit.so.0",
		"libunistring.so.2",
		"libtasn1.so.6",
		"libnettle.so.6",
		"libhogweed.so.4",
		"libgmp.so.10",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libp11-kit.so.0": {[]string{
		"libffi.so.6",
		"libdl.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libffi.so.6": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libunistring.so.2": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libtasn1.so.6": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libnettle.so.6": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libhogweed.so.4": {[]string{
		"libnettle.so.6",
		"libgmp.so.10",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgmp.so.10": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsamdb.so.0": {[]string{
		"libkrb5-samba4.so.26",
		"libsamba-util.so.0",
		"libsamdb-common-samba4.so",
		"libcli-ldap-common-samba4.so",
		"libauthkrb5-samba4.so",
		"libsamba-errors.so.1",
		"libsamba-hostconfig.so.0",
		"libldbsamba-samba4.so",
		"libcliauth-samba4.so",
		"libsamba-credentials.so.0",
		"libkrb5samba-samba4.so",
		"libsamba-security-samba4.so",
		"libndr.so.0",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libgssapi-samba4.so.2",
		"libldb.so.1",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libsamdb-common-samba4.so": {[]string{
		"libpthread.so.0",
		"libflag-mapping-samba4.so",
		"libcli-ldap-common-samba4.so",
		"libndr-samba-samba4.so",
		"libsamba-hostconfig.so.0",
		"libsamba-sockets-samba4.so",
		"libsamba-util.so.0",
		"libsamba-errors.so.1",
		"libndr.so.0",
		"libsamba-security-samba4.so",
		"libsocket-blocking-samba4.so",
		"libtevent-util.so.0",
		"libsamba-debug-samba4.so",
		"libldb.so.1",
		"libtalloc.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libflag-mapping-samba4.so": {[]string{
		"libsamba-debug-samba4.so",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libldbsamba-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libsamdb-common-samba4.so",
		"libndr-samba-samba4.so",
		"libsamba-errors.so.1",
		"libsamba-hostconfig.so.0",
		"libndr.so.0",
		"libsamba-security-samba4.so",
		"libsamba-debug-samba4.so",
		"libndr-standard.so.0",
		"libasn1util-samba4.so",
		"libldb.so.1",
		"libtalloc.so.2",
		"libtdb.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libsamba-credentials.so.0": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libsamdb-common-samba4.so",
		"libcom_err-samba4.so.0",
		"libgssapi-samba4.so.2",
		"libsamba-errors.so.1",
		"libsamba-hostconfig.so.0",
		"libldbsamba-samba4.so",
		"libcliauth-samba4.so",
		"libndr.so.0",
		"libdbwrap-samba4.so",
		"libauthkrb5-samba4.so",
		"libutil-tdb-samba4.so",
		"libkrb5samba-samba4.so",
		"libsamba-security-samba4.so",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libkrb5-samba4.so.26",
		"libldb.so.1",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libgse-samba4.so": {[]string{
		"libpthread.so.0",
		"libkrb5-samba4.so.26",
		"libaddns-samba4.so",
		"libsamba-util.so.0",
		"libgssapi-samba4.so.2",
		"libcli-cldap-samba4.so",
		"libCHARSET3-samba4.so",
		"libsmbconf.so.0",
		"libkrb5samba-samba4.so",
		"libsecrets3-samba4.so",
		"libsamba-sockets-samba4.so",
		"libgensec-samba4.so",
		"libcom_err-samba4.so.0",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libsamba-errors.so.1",
		"libtevent-util.so.0",
		"libsamba3-util-samba4.so",
		"libauthkrb5-samba4.so",
		"libsamba-credentials.so.0",
		"libcli-nbt-samba4.so",
		"libldap-2.4.so.2",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libaddns-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libndr.so.0",
		"libgssapi-samba4.so.2",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libsamba-errors.so.1",
		"libresolv.so.2",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libsmbconf.so.0": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libinterfaces-samba4.so",
		"libtalloc-report-samba4.so",
		"libtevent-util.so.0",
		"libmessages-dgm-samba4.so",
		"libsmbd-shim-samba4.so",
		"libserver-id-db-samba4.so",
		"libsamba-errors.so.1",
		"libdbwrap-samba4.so",
		"libCHARSET3-samba4.so",
		"libiov-buf-samba4.so",
		"libutil-tdb-samba4.so",
		"libndr.so.0",
		"libcli-smb-common-samba4.so",
		"libsamba-cluster-support-samba4.so",
		"libsys-rw-samba4.so",
		"libutil-reg-samba4.so",
		"libsamba3-util-samba4.so",
		"libsocket-blocking-samba4.so",
		"libsamba-sockets-samba4.so",
		"libsamba-security-samba4.so",
		"libmessages-util-samba4.so",
		"libtime-basic-samba4.so",
		"libutil-setid-samba4.so",
		"libsamba-debug-samba4.so",
		"libtdb-wrap-samba4.so",
		"libsamba-hostconfig.so.0",
		"libsmb-transport-samba4.so",
		"libserver-role-samba4.so",
		"libndr-standard.so.0",
		"libtalloc.so.2",
		"libnsl.so.1",
		"libtdb.so.1",
		"libcap.so.2",
		"liblber-2.4.so.2",
		"libbsd.so.0",
		"libldap-2.4.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libtalloc-report-samba4.so": {[]string{
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libmessages-dgm-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libtevent-util.so.0",
		"libmsghdr-samba4.so",
		"libsocket-blocking-samba4.so",
		"libiov-buf-samba4.so",
		"librt.so.1",
		"libtalloc.so.2",
		"libbsd.so.0",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libmsghdr-samba4.so": {[]string{
		"libpthread.so.0",
		"libiov-buf-samba4.so",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libsmbd-shim-samba4.so": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba"}},
	"/lib64/samba/libserver-id-db-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libtdb-wrap-samba4.so",
		"libutil-tdb-samba4.so",
		"libtdb.so.1",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libsamba-cluster-support-samba4.so": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libutil-reg-samba4.so": {[]string{
		"libndr.so.0",
		"libsamba-util.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64"}},
	"/lib64/samba/libmessages-util-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64"}},
	"/lib64/libnsl.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libcap.so.2": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/liblber-2.4.so.2": {[]string{
		"libresolv.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libldap-2.4.so.2": {[]string{
		"liblber-2.4.so.2",
		"libresolv.so.2",
		"libsasl2.so.3",
		"libgnutls.so.30",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsasl2.so.3": {[]string{
		"libdl.so.2",
		"libresolv.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/samba/libsecrets3-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libsmbconf.so.0",
		"libutil-tdb-samba4.so",
		"libndr.so.0",
		"libdbwrap-samba4.so",
		"libsamba-security-samba4.so",
		"libsamba-debug-samba4.so",
		"libgenrand-samba4.so",
		"libsamba3-util-samba4.so",
		"libcliauth-samba4.so",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libcli-nbt-samba4.so": {[]string{
		"libpthread.so.0",
		"libsamba-util.so.0",
		"libtevent-util.so.0",
		"libndr-nbt.so.0",
		"libndr.so.0",
		"libsamba-sockets-samba4.so",
		"libsamba-debug-samba4.so",
		"libsamba-errors.so.1",
		"libtalloc.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libutil-cmdline-samba4.so": {[]string{
		"libsecrets3-samba4.so",
		"libsamba-util.so.0",
		"libsmbconf.so.0",
		"libsamba-errors.so.1",
		"libsamba-hostconfig.so.0",
		"libsamba-credentials.so.0",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libdcerpc-binding.so.0": {[]string{
		"libpthread.so.0",
		"libtevent-util.so.0",
		"libsamba-sockets-samba4.so",
		"libndr.so.0",
		"libgensec-samba4.so",
		"libsamba-errors.so.1",
		"libsamba-util.so.0",
		"libsamba-debug-samba4.so",
		"libtalloc.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/libdcerpc-samba-samba4.so": {[]string{
		"libdcerpc-binding.so.0",
		"libndr-samba-samba4.so",
		"libndr-standard.so.0",
		"libndr.so.0",
		"libtevent-util.so.0",
		"libtalloc.so.2",
		"libtevent.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/samba/liblibcli-lsa3-samba4.so": {[]string{
		"libsamba-util.so.0",
		"libdcerpc-samba-samba4.so",
		"libsamba-debug-samba4.so",
		"libsamba-security-samba4.so",
		"libsamba-errors.so.1",
		"libtalloc.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/samba:/lib64"}},
	"/lib64/libFLAC.so.8": {[]string{
		"libogg.so.0",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libogg.so.0": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libyajl.so.2": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libavahi-common.so.3": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libavahi-client.so.3": {[]string{
		"libdbus-1.so.3",
		"libavahi-common.so.3",
		"libdl.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libdbus-1.so.3": {[]string{
		"libpthread.so.0",
		"libsystemd.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsqlite3.so.0": {[]string{
		"libm.so.6",
		"libdl.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libvorbis.so.0": {[]string{
		"libm.so.6",
		"libogg.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsndfile.so.1": {[]string{
		"libFLAC.so.8",
		"libogg.so.0",
		"libvorbis.so.0",
		"libvorbisenc.so.2",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libvorbisenc.so.2": {[]string{
		"libvorbis.so.0",
		"libm.so.6",
		"libogg.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libaudiofile.so.1": {[]string{
		"libFLAC.so.8",
		"libstdc++.so.6",
		"libm.so.6",
		"libc.so.6",
		"libgcc_s.so.1"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgme.so.0": {[]string{
		"libstdc++.so.6",
		"libm.so.6",
		"libgcc_s.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libwavpack.so.1": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libmad.so.0": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libopus.so.0": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libavformat.so.57": {[]string{
		"libavcodec.so.57",
		"libavutil.so.55",
		"libdl.so.2",
		"libm.so.6",
		"libssh.so.4",
		"libmodplug.so.1",
		"libbluray.so.2",
		"libgnutls.so.30",
		"libgmp.so.10",
		"libbz2.so.1.0",
		"libz.so.1",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libavcodec.so.57": {[]string{
		"libswresample.so.2",
		"libavutil.so.55",
		"libdl.so.2",
		"libva.so.1",
		"libxvidcore.so.4",
		"libx265.so.116",
		"libx264.so.148",
		"libwebpmux.so.3",
		"libwebp.so.7",
		"libvpx.so.4",
		"libm.so.6",
		"libvorbisenc.so.2",
		"libvorbis.so.0",
		"libtheoraenc.so.1",
		"libtheoradec.so.1",
		"libspeex.so.1",
		"libschroedinger-1.0.so.0",
		"libopus.so.0",
		"libopenjp2.so.7",
		"libopencore-amrwb.so.0",
		"libopencore-amrnb.so.0",
		"libmp3lame.so.0",
		"libgsm.so.1",
		"liblzma.so.5",
		"libz.so.1",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libswresample.so.2": {[]string{
		"libavutil.so.55",
		"libm.so.6",
		"libsoxr.so.0",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libavutil.so.55": {[]string{
		"libdl.so.2",
		"libvdpau.so.1",
		"libva.so.1",
		"libva-x11.so.1",
		"libX11.so.6",
		"libva-drm.so.1",
		"libm.so.6",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libvdpau.so.1": {[]string{
		"libdl.so.2",
		"libXext.so.6",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libXext.so.6": {[]string{
		"libX11.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libX11.so.6": {[]string{
		"libxcb.so.1",
		"libdl.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libxcb.so.1": {[]string{
		"libXau.so.6",
		"libXdmcp.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libXau.so.6": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libXdmcp.so.6": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libva.so.1": {[]string{
		"libdl.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libva-x11.so.1": {[]string{
		"libva.so.1",
		"libX11.so.6",
		"libXext.so.6",
		"libXfixes.so.3",
		"libdrm.so.2",
		"libdl.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libXfixes.so.3": {[]string{
		"libX11.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libdrm.so.2": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libva-drm.so.1": {[]string{
		"libva.so.1",
		"libdrm.so.2",
		"libdl.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsoxr.so.0": {[]string{
		"libm.so.6",
		"libgomp.so.1",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgomp.so.1": {[]string{
		"libdl.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libxvidcore.so.4": {[]string{
		"libc.so.6",
		"libm.so.6",
		"libpthread.so.0"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libx265.so.116": {[]string{
		"libpthread.so.0",
		"libdl.so.2",
		"libstdc++.so.6",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libx264.so.148": {[]string{
		"libc.so.6",
		"libm.so.6",
		"libpthread.so.0",
		"libdl.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libwebpmux.so.3": {[]string{
		"libwebp.so.7",
		"libm.so.6",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libwebp.so.7": {[]string{
		"libm.so.6",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libvpx.so.4": {[]string{
		"libpthread.so.0",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libtheoraenc.so.1": {[]string{
		"libogg.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libtheoradec.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libspeex.so.1": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libschroedinger-1.0.so.0": {[]string{
		"liborc-0.4.so.0",
		"libpthread.so.0",
		"libstdc++.so.6",
		"libm.so.6",
		"libc.so.6",
		"libgcc_s.so.1"},
		[]string(nil),
		[]string(nil)},
	"/lib64/liborc-0.4.so.0": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libopenjp2.so.7": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libopencore-amrwb.so.0": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libopencore-amrnb.so.0": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libmp3lame.so.0": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgsm.so.1": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libssh.so.4": {[]string{
		"librt.so.1",
		"libgcrypt.so.20",
		"libz.so.1",
		"libc.so.6",
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libmodplug.so.1": {[]string{
		"libstdc++.so.6",
		"libm.so.6",
		"libc.so.6",
		"libgcc_s.so.1"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libbluray.so.2": {[]string{
		"libxml2.so.2",
		"libfontconfig.so.1",
		"libfreetype.so.6",
		"libdl.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libxml2.so.2": {[]string{
		"libdl.so.2",
		"libicuuc.so.59",
		"libz.so.1",
		"liblzma.so.5",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libfontconfig.so.1": {[]string{
		"libfreetype.so.6",
		"libexpat.so.1",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libfreetype.so.6": {[]string{
		"libz.so.1",
		"libbz2.so.1.0",
		"libpng16.so.16",
		"libharfbuzz.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libbz2.so.1.0": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libpng16.so.16": {[]string{
		"libz.so.1",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libharfbuzz.so.0": {[]string{
		"libglib-2.0.so.0",
		"libfreetype.so.6",
		"libgraphite2.so.3",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libglib-2.0.so.0": {[]string{
		"libpcre.so.1",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libpcre.so.1": {[]string{
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libgraphite2.so.3": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libfaad.so.2": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libcdio_paranoia.so.2": {[]string{
		"libcdio_cdda.so.2",
		"libcdio.so.16",
		"librt.so.1",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libcdio_cdda.so.2": {[]string{
		"libcdio.so.16",
		"librt.so.1",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libcdio.so.16": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libmms.so.0": {[]string{
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libasound.so.2": {[]string{
		"libm.so.6",
		"libdl.so.2",
		"libpthread.so.0",
		"librt.so.1",
		"libc.so.6",
		"ld-linux-x86-64.so.2"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libiso9660.so.10": {[]string{
		"libcdio.so.16",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libzzip-0.so.13": {[]string{
		"libz.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libao.so.4": {[]string{
		"libpthread.so.0",
		"libdl.so.2",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libjack.so.0": {[]string{
		"libpthread.so.0",
		"librt.so.1",
		"libdl.so.2",
		"libstdc++.so.6",
		"libm.so.6",
		"libgcc_s.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libshout.so.3": {[]string{
		"libvorbis.so.0",
		"libssl.so.1.1",
		"libcrypto.so.1.1",
		"libspeex.so.1",
		"libtheora.so.0",
		"libogg.so.0",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libtheora.so.0": {[]string{
		"libogg.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libpulse.so.0": {[]string{
		"libpulsecommon-10.0.so",
		"libdbus-1.so.3",
		"libpthread.so.0",
		"libdl.so.2",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string{"/lib64/pulseaudio"}},
	"/lib64/pulseaudio/libpulsecommon-10.0.so": {[]string{
		"libxcb.so.1",
		"libsystemd.so.0",
		"libsndfile.so.1",
		"libasyncns.so.0",
		"libdbus-1.so.3",
		"libpthread.so.0",
		"librt.so.1",
		"libdl.so.2",
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libasyncns.so.0": {[]string{
		"libresolv.so.2",
		"libpthread.so.0",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libid3tag.so.0": {[]string{
		"libz.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libsamplerate.so.0": {[]string{
		"libm.so.6",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
	"/lib64/libicui18n.so.59": {[]string{
		"libicuuc.so.59",
		"libstdc++.so.6",
		"libm.so.6",
		"libgcc_s.so.1",
		"libc.so.6"},
		[]string(nil),
		[]string(nil)},
}

var mpdresolved = []string{
	"/lib64/samba/libkrb5samba-samba4.so",
	"/lib64/libxcb.so.1",
	"/lib64/libmms.so.0",
	"/lib64/libsamplerate.so.0",
	"/lib64/libupnp.so.6",
	"/lib64/libssl.so.1.1",
	"/lib64/samba/libcli-cldap-samba4.so",
	"/lib64/samba/libcliauth-samba4.so",
	"/lib64/samba/libsamba-modules-samba4.so",
	"/lib64/samba/libkrb5-samba4.so.26",
	"/lib64/samba/libasn1-samba4.so.8",
	"/lib64/samba/libhx509-samba4.so.5",
	"/lib64/libtalloc.so.2",
	"/lib64/samba/libasn1util-samba4.so",
	"/lib64/libopencore-amrwb.so.0",
	"/lib64/libharfbuzz.so.0",
	"/lib64/libnsl.so.1",
	"/lib64/libspeex.so.1",
	"/lib64/libschroedinger-1.0.so.0",
	"/lib64/libmp3lame.so.0",
	"/lib64/samba/libauthkrb5-samba4.so",
	"/lib64/libwebp.so.7",
	"/lib64/samba/libsamba-security-samba4.so",
	"/lib64/libndr-standard.so.0",
	"/lib64/samba/libmessages-util-samba4.so",
	"/lib64/libFLAC.so.8",
	"/lib64/libavahi-common.so.3",
	"/lib64/libdbus-1.so.3",
	"/lib64/libixml.so.2",
	"/lib64/libresolv.so.2",
	"/lib64/libopencore-amrnb.so.0",
	"/lib64/samba/libinterfaces-samba4.so",
	"/lib64/samba/libcli-ldap-common-samba4.so",
	"/lib64/samba/libgssapi-samba4.so.2",
	"/lib64/libhogweed.so.4",
	"/lib64/libsndfile.so.1",
	"/lib64/libXext.so.6",
	"/lib64/libgcc_s.so.1",
	"/lib64/libcom_err.so.2",
	"/lib64/libsamba-hostconfig.so.0",
	"/lib64/samba/libgensec-samba4.so",
	"/lib64/libsamdb.so.0",
	"/lib64/libXfixes.so.3",
	"/lib64/libgssapi_krb5.so.2",
	"/lib64/libsmbclient.so.0",
	"/lib64/libopus.so.0",
	"/lib64/libx264.so.148",
	"/lib64/libvpx.so.4",
	"/lib64/libpng16.so.16",
	"/lib64/libyajl.so.2",
	"/lib64/libsqlite3.so.0",
	"/lib64/libgpg-error.so.0",
	"/lib64/libndr.so.0",
	"/lib64/libunistring.so.2",
	"/lib64/libcap.so.2",
	"/lib64/libasyncns.so.0",
	"/lib64/libpthread.so.0",
	"/lib64/libsamba-util.so.0",
	"/lib64/librt.so.1",
	"/lib64/libndr-krb5pac.so.0",
	"/lib64/libwavpack.so.1",
	"/lib64/libfontconfig.so.1",
	"/lib64/libdl.so.2",
	"/lib64/libkrb5.so.3",
	"/lib64/samba/libCHARSET3-samba4.so",
	"/lib64/samba/libtalloc-report-samba4.so",
	"/lib64/samba/libmessages-dgm-samba4.so",
	"/lib64/libXdmcp.so.6",
	"/lib64/libasound.so.2",
	"/lib64/libpulse.so.0",
	"/lib64/libicudata.so.59",
	"/lib64/samba/libiov-buf-samba4.so",
	"/lib64/libgcrypt.so.20",
	"/lib64/libgnutls.so.30",
	"/lib64/libgmp.so.10",
	"/lib64/libswresample.so.2",
	"/lib64/libavutil.so.55",
	"/lib64/libicuuc.so.59",
	"/lib64/libm.so.6",
	"/lib64/samba/libutil-cmdline-samba4.so",
	"/lib64/libmad.so.0",
	"/lib64/libiso9660.so.10",
	"/lib64/libao.so.4",
	"/lib64/libcurl.so.4",
	"/lib64/libcrypto.so.1.1",
	"/lib64/libtdb.so.1",
	"/lib64/samba/libcom_err-samba4.so.0",
	"/lib64/samba/libwind-samba4.so.0",
	"/lib64/samba/libutil-reg-samba4.so",
	"/lib64/samba/liblibcli-lsa3-samba4.so",
	"/lib64/libbluray.so.2",
	"/lib64/libssh2.so.1",
	"/lib64/libsystemd.so.0",
	"/lib64/libfaad.so.2",
	"/lib64/libjack.so.0",
	"/lib64/libwebpmux.so.3",
	"/lib64/samba/libsamdb-common-samba4.so",
	"/lib64/samba/libldbsamba-samba4.so",
	"/lib64/libavahi-client.so.3",
	"/lib64/libva.so.1",
	"/lib64/libxvidcore.so.4",
	"/lib64/libldap-2.4.so.2",
	"/lib64/libsasl2.so.3",
	"/lib64/samba/libsamba3-util-samba4.so",
	"/lib64/libwbclient.so.0",
	"/lib64/samba/libauth-sam-reply-samba4.so",
	"/lib64/samba/libdcerpc-samba-samba4.so",
	"/lib64/libogg.so.0",
	"/lib64/libdrm.so.2",
	"/lib64/samba/libtime-basic-samba4.so",
	"/lib64/samba/libdbwrap-samba4.so",
	"/lib64/libsoxr.so.0",
	"/lib64/samba/libsamba-debug-samba4.so",
	"/lib64/libnettle.so.6",
	"/lib64/libx265.so.116",
	"/lib64/libopenjp2.so.7",
	"/lib64/libcdio_paranoia.so.2",
	"/usr/bin/mpd",
	"/lib64/libz.so.1",
	"/lib64/samba/libutil-tdb-samba4.so",
	"/lib64/samba/libndr-samba-samba4.so",
	"/lib64/libX11.so.6",
	"/lib64/libva-drm.so.1",
	"/lib64/libtheoradec.so.1",
	"/lib64/libkrb5support.so.0",
	"/lib64/libkeyutils.so.1",
	"/lib64/libfreetype.so.6",
	"/lib64/libsamba-credentials.so.0",
	"/lib64/libgomp.so.1",
	"/lib64/libaudiofile.so.1",
	"/lib64/libXau.so.6",
	"/lib64/libstdc++.so.6",
	"/lib64/samba/libtdb-wrap-samba4.so",
	"/lib64/libgme.so.0",
	"/lib64/libcdio.so.16",
	"/lib64/ld-linux-x86-64.so.2",
	"/lib64/samba/libcli-nbt-samba4.so",
	"/lib64/libldb.so.1",
	"/lib64/samba/libserver-role-samba4.so",
	"/lib64/libvorbis.so.0",
	"/lib64/libvorbisenc.so.2",
	"/lib64/pulseaudio/libpulsecommon-10.0.so",
	"/lib64/libicui18n.so.59",
	"/lib64/liblzma.so.5",
	"/lib64/libtevent-util.so.0",
	"/lib64/libmodplug.so.1",
	"/lib64/libk5crypto.so.3",
	"/lib64/samba/libsamba-sockets-samba4.so",
	"/lib64/libbz2.so.1.0",
	"/lib64/libglib-2.0.so.0",
	"/lib64/samba/libreplace-samba4.so",
	"/lib64/libffi.so.6",
	"/lib64/samba/libutil-setid-samba4.so",
	"/lib64/samba/libsmb-transport-samba4.so",
	"/lib64/samba/libwinbind-client-samba4.so",
	"/lib64/libsmbconf.so.0",
	"/lib64/libavformat.so.57",
	"/lib64/libtheora.so.0",
	"/lib64/libnghttp2.so.14",
	"/lib64/libtevent.so.0",
	"/lib64/samba/libgse-samba4.so",
	"/lib64/samba/libsamba-cluster-support-samba4.so",
	"/lib64/liblber-2.4.so.2",
	"/lib64/libtheoraenc.so.1",
	"/lib64/libthreadutil.so.6",
	"/lib64/libndr-nbt.so.0",
	"/lib64/samba/liblibsmb-samba4.so",
	"/lib64/samba/libhcrypto-samba4.so.5",
	"/lib64/libtasn1.so.6",
	"/lib64/samba/libflag-mapping-samba4.so",
	"/lib64/liborc-0.4.so.0",
	"/lib64/libssh.so.4",
	"/lib64/libmpdclient.so.2",
	"/lib64/liblz4.so.1",
	"/lib64/libcdio_cdda.so.2",
	"/lib64/libid3tag.so.0",
	"/lib64/samba/libroken-samba4.so.19",
	"/lib64/libp11-kit.so.0",
	"/lib64/libvdpau.so.1",
	"/lib64/libpcre.so.1",
	"/lib64/libexpat.so.1",
	"/lib64/libsamba-errors.so.1",
	"/lib64/samba/libaddns-samba4.so",
	"/lib64/libxml2.so.2",
	"/lib64/libgraphite2.so.3",
	"/lib64/libc.so.6",
	"/lib64/libbsd.so.0",
	"/lib64/samba/libserver-id-db-samba4.so",
	"/lib64/libva-x11.so.1",
	"/lib64/libgsm.so.1",
	"/lib64/libzzip-0.so.13",
	"/lib64/libpsl.so.5",
	"/lib64/samba/libcli-smb-common-samba4.so",
	"/lib64/samba/libheimbase-samba4.so.1",
	"/lib64/samba/libsmbd-shim-samba4.so",
	"/lib64/samba/libsecrets3-samba4.so",
	"/lib64/libdcerpc-binding.so.0",
	"/lib64/libavcodec.so.57",
	"/lib64/libshout.so.3",
	"/lib64/libnfs.so.11",
	"/lib64/samba/libsocket-blocking-samba4.so",
	"/lib64/samba/libmsrpc3-samba4.so",
	"/lib64/samba/libmsghdr-samba4.so",
	"/lib64/samba/libgenrand-samba4.so",
	"/lib64/samba/libsys-rw-samba4.so",
}
